export const images = {
  Splash: require("../../assets/splash.png"),
  AppIcon: require("../../assets/icon.png"),
  LightBulb: require("../../assets/lightbulb.webp"),
  SadEgg: require("../../assets/sadegg.jpg"),
  StarBoy: require("../../assets/starboy.webp"),
  Duck: require("../../assets/duck.png"),
  Book1: require("../../assets/book1.webp"),
  Book2: require("../../assets/book2.webp"),
  Book3: require("../../assets/book3.webp"),
  Book4: require("../../assets/book4.webp"),
  MyBook1: require("../../assets/mybook1.png"),
  MyBook2: require("../../assets/mybook2.png"),
  MyBook3: require("../../assets/mybook3.png"),
  MyBook4: require("../../assets/mybook4.png"),
};
