export const images = {
  Splash: require("../../assets/splash.png"),
  AppIcon: require("../../assets/icon.png"),
  LightBulb: require("../../assets/lightbulb.jpg"),
  SadEgg: require("../../assets/sadegg.jpg"),
  StarBoy: require("../../assets/starboy.jpg"),
  Duck: require("../../assets/duck.jpg"),
  Book1: require("../../assets/book1.jpg"),
  Book2: require("../../assets/book2.jpg"),
  Book3: require("../../assets/book3.jpg"),
  Book4: require("../../assets/book4.jpg"),
  MyBook1: require("../../assets/mybook1.jpg"),
  MyBook2: require("../../assets/mybook2.jpg"),
  MyBook3: require("../../assets/mybook3.jpg"),
  MyBook4: require("../../assets/mybook4.jpg"),
};
